#!/bin/bash
exec
	version_gt() { 
		test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; 
		first_version=$1
		second_version=$2
		if version_gt $first_version $second_version; then
			ture;     
			echo "$first_version is greater than $second_version !"
		else
			false;
			echo "$first_version is lesser than $second_version !"
		fi
	};
