#!/bin/bash
exec 
	mkvextract $1 tracks $2:$1.sub;
	sed -i -e 's/\[.*//mg' $1.sub;
	sed -i -e 's/♪//mg' $1.sub;
	sed -i -e 's/\*.*//mg' $1.sub;
	sed -i -e 's/.*\]//mg' $1.sub;
	echo "Done creating file: $1.sub";
