#!/bin/bash
exec
	CURRENT="$(  gitkraken --version | tail -n 1 | sed 's/\.//g' )";	
	LATEST="$( curl -s https://www.gitkraken.com/download | grep 'Latest release' | cut -d ':' -f 2 | cut -d '<' -f 1 | sed 's/\.//g' )";
	echo "Comparing versions...";
	if [ "$LATEST" -gt "$CURRENT" ]
		then
			echo "Updating to latest version..."
			sudo mkdir /tmp/gitkraken;
			cd /tmp/gitkraken;
			curl -LO https://release.gitkraken.com/linux/gitkraken-amd64.deb;
			sudo dpkg -i ./*deb;
			cd;
			sudo rm -R /tmp/gitkraken;
		else
			echo "Gitkraken up to date."	
	fi
