#!bin/bash

# CURRENT='$( curl -s https://launchpad.net/grub-customizer | grep 'Latest version is ' | cut -d ' ' -f 8 )'

sudo mkdir /tmp/grub-cstm-tart;
cd /tmp/grub-cstm-tart;
sudo curl -LO https://launchpad.net/grub-customizer/5.0/5.0.6/+download/grub-customizer_5.0.6.tar.gz
sudo tar xvf ./grub-customizer_5.0.6.tar.gz;
cd ./grub-customizer-5.0.6;
cmake .;
make;
sudo make install;
cd;
sudo rm -R /tmp/grub-cstm-tart; 
