#!/bin/bash
exec

	function update-dbeaver-deb {
    	echo "Updating DBeaver...";
		sudo mkdir /tmp/dbeaver-deb;
     	cd /tmp/dbeaver-deb;
     	sudo curl -LO https://dbeaver.jkiss.org/files/dbeaver-ce_latest_amd64.deb;
     	sudo dpkg -i ./*deb;
     	cd;
     	sudo rm -R /tmp/dbeaver-deb;
		echo "DBeaver updated.";
	};

	CURRENT="$( sudo dpkg --list | grep beaver | cut -d " " -f 43 )";
	LATEST="$( curl -s https://dbeaver.jkiss.org/download/ | grep "<h2>Community Edition" | cut -d ' ' -f3 | cut -d '<' -f1 )";

	function version_gt() { 
		echo "Comparing DBeaver versions: current($CURRENT) with latest($LATEST)...";
	  	test "$(printf '%s\n' "$@" | sort -V | head -n 1)" != "$1"; 
	}
	
	if version_gt "$LATEST" "$CURRENT" ; then
		update-dbeaver-deb
	else
		echo "DBeaver up to date."	
	fi

